# Generated by Django 2.0 on 2018-10-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('email', models.CharField(db_index=True, max_length=64)),
                ('number', models.CharField(db_index=True, max_length=32)),
            ],
        ),
    ]
